[config]
cache_dir = ".yoita/cache"
staging_dir = ".yoita/staging"
mount_dir = "./mods"

[steam]
download_endpoint = "https://your-downloader.example/workshop/download"

[mods]
edit-always = {}
wanddbg = { workshop_id = "3454128340" }
