[config]
cache_dir = ".yoita/cache"
staging_dir = ".yoita/staging"
mount_dir = "./mods"

[steam]
backend = "steamcmd"
steamcmd_path = "steamcmd"
force_install_dir = ".yoita/steamcmd"
app_id = 881100
timeout_secs = 300
login = "anonymous"

[mods]
edit-always = {}
wanddbg = { workshop_id = "3454128340" }
